### PR TITLE
fix for going to next job

### PR DESCRIPTION
**Pull request by sumitkumar1209**
go to next job only if current timeout has happened to avoid throttling

### CODE REVIEW

**Comment by fent** [comment]
Can you explain what this does? I'm not understanding it from the code or comment.

**Comment by sumitkumar1209** [comment]
each queue has a timeout, so according to your code if current queue finishes before its timeout it will go to the next job which can cause error response from the server as the request is not throttled.

this code waits until the current timeout is expired then would go to next job.

**Comment by fent** [comment]
On the first `(+new Date() - everyTime)`, it will always be equal to `every`, which would make the call to `setTimeout()` redundant. Unless it's intentionally calling `.next()` on the next event loop.

For the second case, it would only be called if the task took longer than `every`, so the time that `setTimeout()` is called with would be negative.

**Comment by sumitkumar1209** [comment]
yeah, you are right. may at that time I didn't notice that you are pushing into `self._timers` only after timeout has happened for every single task. So both setTImeout are nullified. I will delete this pull request and close the conversation.

**Comment by sumitkumar1209** [comment]
Looks like I can't delete this.

**Comment by fent** [comment]
Closed is fine. Thanks.

**Pull request closed without merging**
